# Generated by Django 4.0 on 2022-11-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0004_movie_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carausel',
        ),
    ]
