# Generated by Django 4.0 on 2022-11-25 05:13

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0007_reserve_movie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
