# Generated by Django 4.0 on 2022-11-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0011_alter_reserve_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='quantity',
            field=models.IntegerField(choices=[('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], default=0, null=True),
        ),
    ]
