# Generated by Django 4.0 on 2022-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0012_alter_reserve_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='quantity',
            field=models.IntegerField(choices=[('Zero', '0'), ('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10')], default=0, null=True),
        ),
    ]
