# Generated by Django 4.0 on 2022-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0014_alter_movie_quantity_alter_reserve_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='director',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
